name: ci

on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"

concurrency:
  group: ci-workflows
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_ID }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |-
            shelgir/kubak-landing-api:latest
            shelgir/kubak-landing-api:${{ github.sha }}
            shelgir/kubak-landing-api:${{ github.ref_name }}
