name: Deploy to Heroku

on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"

env:
  APP_NAME: kubak-landing-api

concurrency:
  group: heroku-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Heroku Registry
        uses: docker/login-action@v1
        with:
          registry: registry.heroku.com
          username: _
          password: ${{ secrets.HEROKU_API_KEY }}

      # Push the Docker image to Heroku Container Registry
      - name: Publish
        uses: akhileshns/heroku-deploy@v3.12.12
        run: heroku container:push web -a $APP_NAME
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "kubak-landing-api" #Must be unique in Heroku
          heroku_email: "5h4k4r.b4kr@gmail.com"

      - name: Release
        run: heroku container:release web -a $APP_NAME
